source 'https://rubygems.org'
ruby '2.0.0'

gem 'sinatra'
gem 'shotgun'
gem 'rack'
gem 'rack-livereload'
gem 'guard'
gem 'guard-livereload'
gem 'guard-sass'
gem 'sass'
gem 'compass'
gem 'dm-mysql-adapter'
  gem 'sqlite3'
gem 'data_mapper'

