source 'https://rubygems.org'
ruby '2.0.0'

gem 'sinatra'
gem 'shotgun'
gem 'rack'
gem 'rack-livereload'
gem 'guard'
gem 'guard-livereload'
gem 'guard-sass'
gem 'sass'
gem 'compass'
# gem 'dm-sqlite-adapter'
# gem 'sqlite3'
gem 'dm-postgres-adapter'
gem 'pg'
gem 'data_mapper'

